name: modular_customizable_dropdown
description: A modular and customizable dropdown that can be attached to ANY widget.
version: 2.0.1
repository: https://github.com/Khongchai/modular_customizable_dropdown

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0